export const PromptList = [
  "What made you smile today?",
  "One good thing about today was?",
  "What are you looking forward to?",
  "Someone who helped you today?",
  "What did you learn today?",
  "What are you proud of?",
  "A fun memory from today?",
  "What brought you calmness?",
  "One thing you're thankful for?",
  "A delicious meal you had?",
  "What made your heart happy?",
  "A good book you're reading?",
  "What's something new you tried?",
  "A helpful resource you found?",
  "What did you create today?",
  "A lovely conversation you had?",
  "What's something you appreciate?",
  "What made you feel strong?",
  "A funny moment from today?",
  "What did you accomplish?",
  "One thing that made you laugh?",
  "A good friend you have?",
  "What's something you admire?",
  "A happy memory from childhood?",
  "What's one thing you're good at?",
  "One thing you're passionate about?",
  "A fun thing you're planning?",
  "What's one thing you love about yourself?",
  "A good habit you have?",
  "One thing that brings you joy?",
  "A lovely thing someone did for you?",
  "What made you feel appreciated?",
  "What's something you're good at learning?",
  "A peaceful morning you had?",
  "What's one thing you love about your life?",
  "What's something you're excited to learn?",
  "One thing you're proud of accomplishing?",
  "A delicious treat you had?",
  "What's something you love about your culture?",
  "A happy memory from a trip?",
  "One thing you appreciate about your family?",
  "A good thing about your daily routine?",
  "What's something you're looking forward to trying?",
  "One thing you love about your home?",
  "What's one thing you love about your friends?",
  "What made you feel confident today?",
  "One thing you appreciate about your health?",
  "A lovely thing you did for someone else?",
  "A good thing about your favorite hobby?",
  "What's one thing you're excited for in the future?",
  "A happy memory from a special occasion?",
  "What's something you appreciate about your life?",
  "One thing you love about your personality?",
  "What made you feel proud of yourself?",
  "A good thing about your relationships?",
  "What's something you're looking forward to experiencing?",
  "What's one thing you're grateful for in your life?",
  "One thing you appreciate about your resilience?",
  "What made you feel seen today?",
  "A good thing about your self-care routine?",
  "What's something you love about your growth?",
  "One thing you're proud of overcoming?",
  "A lovely thing you learned about yourself?",
  "What's something you appreciate about your support system?",
  "A beautiful thing you have to be thankful for?",
];
