export const PromptList = [
  "What made you smile today?",
  "One good thing about today was?",
  "A simple pleasure you enjoyed?",
  "What are you looking forward to?",
  "Someone who helped you today?",
  "A beautiful thing you saw?",
  "What did you learn today?",
  "A cozy moment you had?",
  "What are you proud of?",
  "A fun memory from today?",
  "What brought you calmness?",
  "One thing you're thankful for?",
  "A delicious meal you had?",
  "What made your heart happy?",
  "A good book you're reading?",
  "What's something new you tried?",
  "A helpful resource you found?",
  "What did you create today?",
  "One thing you're excited for?",
  "A lovely conversation you had?",
  "What's something you appreciate?",
  "A beautiful sunset you saw?",
  "What made you feel strong?",
  "One thing you're grateful for?",
  "A funny moment from today?",
  "What's something you love?",
  "A peaceful spot you found?",
  "What did you accomplish?",
  "One thing that made you laugh?",
  "A good friend you have?",
  "What's something you admire?",
  "A happy memory from childhood?",
  "What's one thing you're good at?",
  "A beautiful flower you saw?",
  "What made your day better?",
  "One thing you're passionate about?",
  "A cozy thing you own?",
  "What's something you're proud to have?",
  "A fun thing you're planning?",
  "What's one thing you love about yourself?",
  "A good habit you have?",
  "What's something you're looking forward to?",
  "One thing that brings you joy?",
  "A lovely thing someone did for you?",
  "What's something you enjoy doing?",
  "A beautiful view you saw?",
  "What made you feel appreciated?",
  "One thing you're thankful to have?",
  "A happy song you heard?",
  "What's something you're good at learning?",
  "A peaceful morning you had?",
  "What's one thing you love about your life?",
  "A funny joke you heard?",
  "What's something you're excited to learn?",
  "One thing you appreciate about your body?",
  "A good thing about your community?",
  "What's something you love about nature?",
  "A beautiful work of art you saw?",
  "What made you feel happy today?",
  "One thing you're proud of accomplishing?",
  "A delicious treat you had?",
  "What's something you love about your culture?",
  "A happy memory from a trip?",
  "What's one thing you're grateful for today?",
  "A lovely thing you own?",
  "What's something you enjoy doing alone?",
  "One thing you appreciate about your family?",
  "A beautiful thing you saw in nature?",
  "What made you feel loved today?",
  "A good thing about your daily routine?",
  "What's something you're looking forward to trying?",
  "One thing you love about your home?",
  "A peaceful thing you do before bed?",
  "What's something you're proud to be a part of?",
  "A happy thing you're anticipating?",
  "What's one thing you love about your friends?",
  "A beautiful thing you created?",
  "What made you feel confident today?",
  "One thing you appreciate about your health?",
  "A lovely thing you did for someone else?",
  "What's something you love about learning?",
  "A good thing about your favorite hobby?",
  "What's one thing you're excited for in the future?",
  "A happy memory from a special occasion?",
  "What's something you appreciate about your life?",
  "One thing you love about your personality?",
  "A beautiful thing you saw today?",
  "What made you feel proud of yourself?",
  "A good thing about your relationships?",
  "What's something you're looking forward to experiencing?",
  "One thing you appreciate about your freedom?",
  "A lovely thing you have to look forward to?",
  "What's something you love about your creativity?",
  "A peaceful thing you do to relax?",
  "What's one thing you're grateful for in your life?",
  "A happy thing you're expecting?",
  "One thing you appreciate about your resilience?",
  "A beautiful thing you're a part of?",
  "What made you feel seen today?",
  "A good thing about your self-care routine?",
  "What's something you love about your growth?",
  "One thing you're proud of overcoming?",
  "A lovely thing you learned about yourself?",
  "What's something you appreciate about your support system?",
  "A beautiful thing you have to be thankful for?",
];
