import React, { useCallback, useEffect, useState } from "react";
import { ScrollView, StyleSheet, View } from "react-native";
import { useAuth } from "../../context/AuthContext";
import { Container } from "../../components/ui/Container";
import AppleSignInPage from "../../components/AppleSignInPage";
import { Link, useFocusEffect, useRouter } from "expo-router";
import { scheduleDailyNotification } from "@/utils/scheduleDailyNotification";
import * as Notifications from "expo-notifications";

import { useUser } from "@/context/UserContext";
import { LargeLink } from "@/components/ui/LargeLink";
import { Header } from "@/components/ui/Header";
import { useMonthlyCount } from "@/context/MonthlyCountProvider";
import { ThemedText } from "@/components/ThemedText";
import { BackendServer } from "@/constants/BackendServer";
import { Button } from "@/components/ui/Button";

const Home = () => {
  const { token } = useAuth();
  const { fetchUserData, preferredUnlockTime } = useUser();
  const { fetchMonthlyCount } = useMonthlyCount();
  const router = useRouter();

  const [monthlyCountData, setMonthlyCountData] = useState<number | null>(null);
  const [loadingData, setLoadingData] = useState<boolean>(true);
  const [serverAvailable, setServerAvailable] = useState<boolean | null>(null);

  const checkServerStatus = useCallback(async () => {
    try {
      const response = await fetch(`${BackendServer}`);
      const data = await response.json();
      const isRunning = data.message === "server running";
      setServerAvailable((prev) => (prev !== isRunning ? isRunning : prev));
    } catch {
      setServerAvailable((prev) => (prev !== false ? false : prev));
    } finally {
    }
  }, []);

  const retry = () => {
    checkServerStatus();
  };

  useEffect(() => {
    const initialize = async () => {
      checkServerStatus();
      const { status } = await Notifications.requestPermissionsAsync();
      if (status !== "granted") {
        console.log("Notification permission not granted");
      }
    };
    initialize();
  }, []);

  useFocusEffect(
    useCallback(() => {
      const asyncFetchData = async () => {
        setLoadingData(true);
        if (token) {
          await fetchUserData();
          if (preferredUnlockTime) {
            scheduleDailyNotification(preferredUnlockTime);
          }
          const count = await fetchMonthlyCount();
          if (typeof count === "number") {
            setMonthlyCountData(count);
          }
        }
        setLoadingData(false);
      };
      asyncFetchData();
    }, [token, preferredUnlockTime])
  );

  if (serverAvailable === false) {
    return (
      <Container style={styles.centered}>
        <ThemedText style={styles.lockedText}>
          Could not connect to server
        </ThemedText>
        <Button
          title={"Retry"}
          onPress={retry}
          variant="outline"
          style={styles.unlockButton}
        />
      </Container>
    );
  }

  if (!token) {
    return (
      <Container style={styles.loginContainer}>
        <View>
          <Header
            title="GratefulTime"
            fontSize={34}
            style={{ marginTop: 0, marginBottom: 100 }}
          />
          <AppleSignInPage />
        </View>
      </Container>
    );
  }

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Container>
        <Header
          title="GratefulTime"
          fontSize={34}
          style={{ marginTop: 160, marginBottom: 40 }}
        />
        <View style={{ marginVertical: 20 }}>
          <ThemedText style={{ fontSize: 24, marginBottom: 10 }}>
            Fill out today's journal
          </ThemedText>
          <LargeLink
            title="Today I'm grateful for"
            onPress={() => router.push("/(tabs)/grateful")}
          />
        </View>
        <View style={{ marginVertical: 20 }}>
          <ThemedText style={{ fontSize: 24, marginBottom: 10 }}>
            Your progress this month
          </ThemedText>
          <LargeLink
            title="This month:"
            data={String(monthlyCountData)}
            loading={loadingData}
            onPress={() => router.push("/(tabs)/calendar")}
          />
        </View>
        <View style={{ marginVertical: 20 }}>
          <ThemedText style={{ fontSize: 24, marginBottom: 10 }}>
            Recap your previous entries
          </ThemedText>
          <LargeLink
            title="AI Summary"
            onPress={() => router.push("/(tabs)/monthlysummary")}
          />
          <ThemedText style={styles.disclaimer}>
            Summaries are generated by Hack Club's{" "}
            <Link
              style={{ color: "#05c3fc" }}
              href="https://github.com/hackclub/ai"
            >
              open source
            </Link>{" "}
            AI service.
          </ThemedText>
        </View>
      </Container>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingBottom: 300,
  },
  loginContainer: {
    justifyContent: "center",
  },
  text: {
    fontSize: 24,
    fontWeight: "600",
  },
  disclaimer: {
    fontSize: 14,
    paddingTop: 20,
    margin: 8,
    color: "#ccc",
    fontStyle: "italic",
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  lockedText: {
    fontSize: 18,
    textAlign: "center",
    paddingBottom: 64,
  },
  unlockButton: {
    paddingHorizontal: 20,
    backgroundColor: "#1c1c1c",
    borderWidth: 1,
    borderColor: "#333",
  },
});

export default Home;
